# Generated by Django 4.2 on 2023-04-30 22:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('online', '0002_remove_product_composition_remove_product_prodapp'),
        ('online', '0003_add_slug_to_product'),
    ]

    operations = [
    ]
